### ISSUE TITLE
Mac OS: Unsafe use of relative rpath (libicudata)

### ISSUE THREAD

**Issue by gentlemich** [brianmario/charlock_holmes#100]
I'm getting the following error since I've upgrade my Mac OS operating system to El Capitan (OS X 10.11). Any idea how to fix it?

/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': dlopen(/Library/Ruby/Gems/2.0.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle, 9): Library not loaded: ../lib/libicudata.54.1.dylib (LoadError)
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle
  Reason: unsafe use of relative rpath ../lib/libicudata.54.1.dylib in /Library/Ruby/Gems/2.0.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle with restricted binary - /Library/Ruby/Gems/2.0.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock_holmes.bundle
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/michael/Sites/upcall/config/application.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by mkdong** [comment]
I have solved this problem by setting DYLD_LIBRARY_PATH to the lib path of icu4c.
See [this issue](https://github.com/Homebrew/brew/issues/2379).

The brew guy says it's the `charlock_holmes` that should fix this, but actually I don't know how.
