### ISSUE TITLE
unable to run server when updating mac brew

### ISSUE THREAD

**Issue by LiamYabou** [brianmario/charlock_holmes#132]
`bundle exec rails c`
```
/Users/liam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.
2.10/lib/active_support/dependencies.rb:274:in `require': dlopen(/Users/lia
m/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.5/lib/
charlock_holmes/charlock_holmes.bundle, 9): Library not loaded: /usr/local/
opt/icu4c/lib/libicudata.60.2.dylib
  Referenced from: /Users/liam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/ge
ms/charlock_holmes-0.7.5/lib/charlock_holmes/charlock_holmes.bundle        b
  Reason: image not found - /Users/liam/.rbenv/versions/2.4.2/lib/ruby/gems
/2.4.0/gems/charlock_holmes-0.7.5/lib/charlock_holmes/charlock_holmes.bundl
e (LoadError)
        from /Users/liam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/act
ivesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in requi
re'
        from /Users/liam/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/act
ivesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependenc
y'

trancated
```
Do you have some idea?

**Comment by anthonyhastings** [comment]
Sounds like you need to recompile `charlock_holmes` because a native dependency it relies on has changed under it's feet. Try uninstalling the gem and re-installing so it'll compile itself using your latest native extensions.
