### ISSUE TITLE
An error occurred while installing charlock_holmes (0.7.6), and Bundler cannot continue. Make sure that `gem install charlock_holmes -v '0.7.6' --source 'http://rubygems.org/'` succeeds before bundling.

### ISSUE THREAD

**Issue by rouor** [brianmario/charlock_holmes#143]
I get following error when try to  install gollum and need help ,thanks.
gemfile:
```
# frozen_string_literal: true

source "http://rubygems.org"

gem 'charlock_holmes', '~> 0.7.6'
gem 'redcarpet'
gem "grit", '~> 2.5.0', git: 'https://github.com/gitlabhq/grit.git', ref: '42297cdcee16284d2e4eff23d41377f52fc28b9d'
gem 'gollum',git: 'https://github.com/gollum/gollum.git'

# gem "rails"
```
---
```
bundle install
Fetching https://github.com/gitlabhq/grit.git
Fetching https://github.com/gollum/gollum.git
Fetching gem metadata from http://rubygems.org/................
Resolving dependencies...
Using bundler 1.17.2
Fetching charlock_holmes 0.7.6
Installing charlock_holmes 0.7.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/rouor/.rvm/gems/ruby-2.6.0/gems/charlock_holmes-0.7.6/ext/charlock_holmes
/Users/rouor/.rvm/rubies/ruby-2.6.0/bin/ruby -I
/Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0 -r
./siteconf20190310-46089-1gzy48j.rb extconf.rb --with-ldflags\=-L.-Wl,-O1\
-Wl,--as-needed\ -rdynamic\ -Wl,-export-dynamic\ -Wl,--no-undefined\ -lz\
-licuuc
checking for -licui18n... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/rouor/.rvm/rubies/ruby-2.6.0/bin/$(RUBY_BASE_NAME)
	--with-icu-dir
	--without-icu-dir
	--with-icu-include
	--without-icu-include=${icu-dir}/include
	--with-icu-lib
	--without-icu-lib=${icu-dir}/lib
	--with-icui18nlib
	--without-icui18nlib
/Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:552:in
`try_link0'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:570:in
`try_link'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:789:in
`try_func'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:1016:in `block
in have_library'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:959:in `block
in checking_for'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:361:in `block
(2 levels) in postpone'
	from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:331:in `open'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:361:in `block
in postpone'
	from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:331:in `open'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:357:in
`postpone'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:958:in
`checking_for'
from /Users/rouor/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/mkmf.rb:1011:in
`have_library'
	from extconf.rb:31:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/Users/rouor/.rvm/gems/ruby-2.6.0/extensions/x86_64-darwin-16/2.6.0/charlock_holmes-0.7.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/rouor/.rvm/gems/ruby-2.6.0/gems/charlock_holmes-0.7.6 for inspection.
Results logged to
/Users/rouor/.rvm/gems/ruby-2.6.0/extensions/x86_64-darwin-16/2.6.0/charlock_holmes-0.7.6/gem_make.out

An error occurred while installing charlock_holmes (0.7.6), and Bundler
cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.6' --source
'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  gollum was resolved to 4.1.4, which depends on
    gollum-lib was resolved to 4.2.10, which depends on
      gollum-grit_adapter was resolved to 1.0.1, which depends on
        gitlab-grit was resolved to 2.8.2, which depends on
          charlock_holmes
```

**Comment by oscarhandsome** [comment]
And how?
