### ISSUE TITLE
Installing charlock_holmes 0.7.6 on Oracle Linux fails 

### ISSUE THREAD

**Issue by pruthvi6767** [brianmario/charlock_holmes#150]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.6/ext/charlock_holmes
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r ./siteconf20191030-23238-uot9nu.rb extconf.rb --with-icu-dir\=/usr/lib/icu
extconf.rb:12: warning: Insecure world writable dir /usr/local/bundle/bin in PATH, mode 040777
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
extconf.rb:12:in ``': No such file or directory - which (Errno::ENOENT)
        from extconf.rb:12:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.6 for inspection.
Results logged to /home/git/gitlab/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/charlock_holmes-0.7.6/gem_make.out

An error occurred while installing charlock_holmes (0.7.6), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.6' --source 'https://cernerrepos.net/api/gems/rubygems/'` succeeds before bundling.

In Gemfile:
  charlock_holmes
```
Tried:
 ```
  yum install libicu-devel

```
      installed icu.50.2 --> din't work

Built ICU4C from source 
```
 git clone https://github.com/unicode-org/icu --depth=1 --branch=release-64-2
 cd icu/icu4c/source && ./configure --prefix=/usr && make install 
```
Then
```
 gem install charlock_holmes -v 0.7.6 --with-icu-dir=/usr/lib/icu
```

**Comment by pruthvi6767** [comment]
Resolved: Dint have https://github.com/brianmario/charlock_holmes/blob/master/ext/charlock_holmes/extconf.rb#L3 installed
